# Generated by Django 5.0.6 on 2024-09-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=180)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=3, default=0.0, max_digits=16)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('email_verification_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('last_active_session', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('invite_code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('investment_personality_points', models.IntegerField(blank=True, null=True)),
                ('investment_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('referral_id', models.IntegerField(blank=True, null=True)),
                ('introducer_fees', models.FloatField(default=0.0)),
                ('is_introducer', models.BooleanField(default=False)),
                ('two_factor_authentication_type', models.TextField(blank=True, choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('AUTHENTICATOR', 'Authenticator')], null=True)),
                ('two_factor_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('total_referred', models.IntegerField(default=0)),
                ('is_distributor', models.BooleanField(default=False)),
                ('has_password_changed', models.BooleanField(default=True)),
                ('distributor_id', models.IntegerField(blank=True, null=True)),
                ('hkd_wallet_balance', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserChatLogin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('token', models.TextField()),
            ],
            options={
                'db_table': 'user_chat_evidai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasicPrompts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prompt_category', models.TextField()),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evidai_prompts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default='default_token', max_length=255)),
                ('title', models.CharField(default='Assisting New Query', max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_sessions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(default='default_token', max_length=255)),
                ('chat_session_id', models.BigIntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'conversations',
                'managed': True,
            },
        ),
    ]
