# Generated by Django 5.0.6 on 2024-09-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidai_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='prompt_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
