# Generated by Django 5.0.6 on 2024-09-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidai_chat', '0002_conversation_prompt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicprompts',
            name='asset_name',
            field=models.TextField(null=True),
        ),
    ]
