# Generated by Django 5.0.6 on 2024-09-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidai_chat', '0003_basicprompts_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
