# Generated by Django 5.0.6 on 2024-09-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidai_chat', '0004_chatsession_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicprompts',
            name='embedding',
        ),
        migrations.AddField(
            model_name='basicprompts',
            name='asset_sub_cat',
            field=models.TextField(null=True),
        ),
    ]
